### ISSUE TITLE
console.image fails when interpreter is paused

### ISSUE THREAD

**Issue by tantalor** [adriancooney/console.snapshot#1]
1. Pause the JavaScript interpreter.
2. From the Chrome devtools console, run `console.image(...)`

Expected: the image immediately appears.

Actual: the image appears after the interpreter is resumed.

**Comment by adriancooney** [comment]
That's unfortunately not something I can fix. You see, to allow for `console.image` to calculate the size of the padding required to print the image on the console, it must request the image via `(new Image).src = url` and retrieve the dimensions. This means the image has to be fully loaded before any printing to the console occurs and thus the image logging is passed as a callback to the `image.onload`. So if the debugger pauses, the callback is left hanging until it resumes.

**Comment by tantalor** [comment]
Fair enough, but what about the `console.screenshot` case? You already know the width and height.

**Comment by adriancooney** [comment]
Ah yes, nice find. Just fixed that! Thanks.
